### ISSUE TITLE
Can you upload the custom ravu any chance?

### ISSUE THREAD

**Issue by toprak** [Artoriuz/miscelaneous#1]
I was looking your mpv conf after reading mpv upscale article(nice article!) I wonder what did you do in 'pc' version so can I have it by anychance :D

**Comment by Artoriuz** [comment]
https://github.com/Artoriuz/miscelaneous/blob/main/ravu-zoom-pc-r3.hook

**Comment by toprak** [comment]
@Artoriuz Thanks, I am new to this stuff using this `~~/shaders/CfL_Prediction.glsl;~~/shaders/ravu-zoom-pc-r3.hook` and adaptive sharpen since I like a bit sharpening, would it cover for anime stuff, I generally watch 1080p stuff on 1080p monitor, or old ones like 480 in 1080p etc. or do you have another recommendation?

**Comment by Artoriuz** [comment]
I use cfl + ravu mostly to watch fhd anime on a qhd display. If you're watching fhd content on a fhd display the luma shader won't do anything.

I think your setup is fine, but if you really want to use adaptive-sharpen I'd probably bind it to a key and only activate it when needed (blurry shows).

**Comment by toprak** [comment]
@Artoriuz Hello it's me again. Firstly, let me say that your new ArtCNN is amazing. So I changed my setup to CfL_Prediction.glsl and ArtCNN_C4F32.glsl I am not expecting you to explain everything so if you know where can I start to learn these terms about mpv, image processing etc. I am ready to learn, why I said it, because I just don't want to use shaders blindly maybe sometimes I need to use other variants such as LL DS DN etc. so yeah. Also, do I have to use antiring and debanding when I use C4F32? I like grains, so maybe should I use static ones?

**Comment by Artoriuz** [comment]
ArtCNN has built-in AR which you can control with glsl-shader-opts.

About debanding, the model is not trained to do any kind of debanding so you do need mpv's debanding if you want to deband the source.

**Comment by toprak** [comment]
@Artoriuz what gpu do you use on this mpv.conf?

**Comment by Artoriuz** [comment]
6600XT
